// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwkyHybTqBKwengGqKrBOlijjaxNVEW-o',
    appId: '1:870433154921:web:e1a521fc09362bfd063ff8',
    messagingSenderId: '870433154921',
    projectId: 'provider-tutorial-45c89',
    authDomain: 'provider-tutorial-45c89.firebaseapp.com',
    storageBucket: 'provider-tutorial-45c89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcBde-3x2p5vIM2ez87truOmWc68TpDMo',
    appId: '1:870433154921:android:501a1ec2bdf1fdb4063ff8',
    messagingSenderId: '870433154921',
    projectId: 'provider-tutorial-45c89',
    storageBucket: 'provider-tutorial-45c89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE9pDvdeOSpywjkGnULgPtl5TxvLrMJKo',
    appId: '1:870433154921:ios:4e3743eaef239865063ff8',
    messagingSenderId: '870433154921',
    projectId: 'provider-tutorial-45c89',
    storageBucket: 'provider-tutorial-45c89.appspot.com',
    androidClientId: '870433154921-0ok19lu0udvg7q17rbasc3tilmuoh706.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectInsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE9pDvdeOSpywjkGnULgPtl5TxvLrMJKo',
    appId: '1:870433154921:ios:4e3743eaef239865063ff8',
    messagingSenderId: '870433154921',
    projectId: 'provider-tutorial-45c89',
    storageBucket: 'provider-tutorial-45c89.appspot.com',
    androidClientId: '870433154921-0ok19lu0udvg7q17rbasc3tilmuoh706.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectInsta',
  );

}